{% set name = "click" %}
{% set version = "7.0" %}

package:
  name: "{{ SURF_SEIS|surf_seis }}"
  version: "{{ 0.1 }}"

source:
  url: https://github.com/cjhopp/SURF_SEIS@packaging

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - cython
    - numpy
    - scipy
    - obspy
    - pillow

test:
  imports:
    - click

about:
  home: https://palletsprojects.com/p/click/
  license: BSD
  license_family: BSD
  summary: Composable command line interface toolkit
